CREATE TYPE OrderStatus AS ENUM ('PENDING_PAYMENT', 'PAID', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'FAILED', 'REFUND_PROCESSING', 'REFUND_COMPLETED', 'RETURN_PROCESSING', 'LOST_OR_DAMAGED');

CREATE TABLE orders (
    order_id TEXT NOT NULL,
    gross_amount INTEGER NOT NULL,
    status OrderStatus NOT NULL DEFAULT 'PENDING_PAYMENT',
    shipping_id VARCHAR(100),
    courier VARCHAR(50) NOT NULL,
    rate_id INTEGER NOT NULL,
    rate_name VARCHAR(50) NOT NULL,
    rate_type VARCHAR(50) NOT NULL,
    cod BOOLEAN NOT NULL DEFAULT false,
    use_insurance BOOLEAN NOT NULL DEFAULT false,
    package_type INTEGER NOT NULL,
    payment_method VARCHAR(50),
    snap_token TEXT NOT NULL,
    snap_redirect_url TEXT NOT NULL,
    user_id VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    buyer VARCHAR(100) NOT NULL,
    length INTEGER NOT NULL,
    width INTEGER NOT NULL,
    height INTEGER NOT NULL,
    weight REAL NOT NULL,
    address_owner VARCHAR(100) NOT NULL,
    street VARCHAR(200) NOT NULL,
    area_id INTEGER NOT NULL,
    area VARCHAR(100) NOT NULL,
    lat VARCHAR(100) NOT NULL,
    lng VARCHAR(100) NOT NULL,
    suburb VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,
    province VARCHAR(100) NOT NULL,
    whatsapp VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(3),
    CONSTRAINT orders_pkey PRIMARY KEY (order_id)
);